name: aplikasipangsitnjedok
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.8 <4.0.0' # Menggunakan rentang yang lebih aman

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Versi ini lebih stabil untuk SDK 3.10

flutter:
  uses-material-design: true

  # Pastikan spasi di bawah ini benar (masuk 2 spasi dari kata flutter)
  assets:
    - assets/images/