// lib/service/pdf_service.dart
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';
import 'dart:typed_data';
import 'dart:math' as math;

class PdfService {
  static Future<Uint8List> generateFinancialReport({
    required String selectedDate,
    required String revenue,
    required String netProfit,
    required List<double> chartData,
    required List<dynamic> bestSelling,
  }) async {
    final pdf = pw.Document();
    
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Container(
            padding: pw.EdgeInsets.all(20),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                // Header
                pw.Text(
                  'Laporan Financial Income',
                  style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.orange800),
                ),
                pw.SizedBox(height: 10),
                pw.Text(
                  'Periode: ${DateFormat('dd MMMM yyyy').format(DateTime.parse(selectedDate))}',
                  style: pw.TextStyle(fontSize: 14, color: PdfColors.grey700),
                ),
                pw.Text(
                  'Tanggal Laporan: ${DateFormat('dd MMMM yyyy HH:mm').format(DateTime.now())}',
                  style: pw.TextStyle(fontSize: 12, color: PdfColors.grey600),
                ),
                pw.Divider(),
                pw.SizedBox(height: 20),
                
                // Summary Cards
                pw.Row(
                  children: [
                    _buildSummaryCard('Total Revenue', revenue),
                    pw.SizedBox(width: 20),
                    _buildSummaryCard('Net Profit (40%)', netProfit),
                  ],
                ),
                pw.SizedBox(height: 30),
                
                // Chart Section
                pw.Text('7 Day Trend', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.brown)),
                pw.SizedBox(height: 16),
                _buildSimpleChart(chartData), // Gunakan versi sederhana
                pw.SizedBox(height: 30),
                
                // Best Selling Section
                pw.Text('Best Selling Products', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.brown)),
                pw.SizedBox(height: 16),
                if (bestSelling.isEmpty)
                  pw.Text('Belum ada data penjualan', style: pw.TextStyle(color: PdfColors.grey600))
                else
                  ...bestSelling.asMap().entries.map((entry) {
                    final item = entry.value;
                    final rank = entry.key + 1;
                    return _buildBestSellingItem(
                      rank: rank,
                      name: item['name'].toString(),
                      sold: int.parse(item['sold'].toString()),
                      amount: item['amount'].toString(),
                    );
                  }),
                
                pw.SizedBox(height: 40),
                pw.Align(
                  alignment: pw.Alignment.center,
                  child: pw.Text(
                    'Generated by Pangsit Njedok App',
                    style: pw.TextStyle(fontSize: 10, color: PdfColors.grey500),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
    
    return pdf.save();
  }
  
  static pw.Container _buildSummaryCard(String title, String value) {
    return pw.Container(
      width: 200,
      padding: pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.orange200),
        borderRadius: pw.BorderRadius.circular(12),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(title, style: pw.TextStyle(color: PdfColors.grey600, fontSize: 11)),
          pw.SizedBox(height: 8),
          pw.Text(
            value,
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: PdfColors.brown),
          ),
        ],
      ),
    );
  }
  
  // VERSI SEDERHANA - Menggunakan Table untuk membuat grafik batang
  static pw.Widget _buildSimpleChart(List<double> points) {
    final maxValue = points.reduce(math.max);
    final minValue = points.reduce(math.min);
    
    return pw.Container(
      padding: pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.orange200),
        borderRadius: pw.BorderRadius.circular(12),
      ),
      child: pw.Column(
        children: [
          // Line Chart using CustomPaint to avoid Axis version compatibility issues
          pw.Container(
            height: 120,
            width: double.infinity,
            child: pw.CustomPaint(
              painter: (PdfGraphics canvas, PdfPoint size) {
                if (points.isEmpty) return;
                
                final w = size.x;
                final h = size.y;
                final stepX = w / (points.length > 1 ? points.length - 1 : 1);
                
                // Draw the line
                canvas.setColor(PdfColors.orange400);
                canvas.setLineWidth(2.0);
                
                for (int i = 0; i < points.length; i++) {
                  final x = i * stepX;
                  final y = (points[i] / (maxValue == 0 ? 1 : maxValue)) * h;
                  if (i == 0) {
                    canvas.moveTo(x, y);
                  } else {
                    final prevX = (i - 1) * stepX;
                    final prevY = (points[i - 1] / (maxValue == 0 ? 1 : maxValue)) * h;
                    
                    final cp1X = prevX + (x - prevX) / 2;
                    final cp1Y = prevY;
                    final cp2X = x - (x - prevX) / 2;
                    final cp2Y = y;
                    
                    canvas.curveTo(cp1X, cp1Y, cp2X, cp2Y, x, y);
                  }
                }
                canvas.strokePath();
                
                // Draw the points
                canvas.setColor(PdfColors.orange700);
                for (int i = 0; i < points.length; i++) {
                  final x = i * stepX;
                  final y = (points[i] / (maxValue == 0 ? 1 : maxValue)) * h;
                  canvas.drawEllipse(x, y, 3, 3);
                  canvas.fillPath();
                }
              },
            ),
          ),
          
          pw.SizedBox(height: 10),
          
          // Header hari (X Axis)
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: List.generate(points.length, (index) {
              final date = DateTime.now().subtract(Duration(days: points.length - 1 - index));
              return pw.Text(
                DateFormat('E').format(date),
                style: pw.TextStyle(fontSize: 8, color: PdfColors.grey700),
                textAlign: pw.TextAlign.center,
              );
            }),
          ),
          
          pw.SizedBox(height: 16),
          
          // Nilai min dan max
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('Min: ${(minValue * 100).toStringAsFixed(0)}%', style: pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
              pw.Text('Max: ${(maxValue * 100).toStringAsFixed(0)}%', style: pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
            ],
          ),
        ],
      ),
    );
  }
  
  static pw.Container _buildBestSellingItem({
    required int rank,
    required String name,
    required int sold,
    required String amount,
  }) {
    final bool isTop = rank <= 3;
    
    return pw.Container(
      margin: pw.EdgeInsets.only(bottom: 12),
      padding: pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: isTop ? PdfColors.orange50 : PdfColors.white,
        border: pw.Border.all(color: isTop ? PdfColors.orange400 : PdfColors.orange200),
        borderRadius: pw.BorderRadius.circular(16),
      ),
      child: pw.Row(
        children: [
          // Circle untuk nomor rank
          pw.Container(
            width: 32,
            height: 32,
            decoration: pw.BoxDecoration(
              color: isTop ? PdfColors.orange400 : PdfColors.orange200,
              shape: pw.BoxShape.circle,
            ),
            child: pw.Center(
              child: pw.Text(
                '$rank',
                style: pw.TextStyle(color: PdfColors.white, fontWeight: pw.FontWeight.bold, fontSize: 14),
              ),
            ),
          ),
          pw.SizedBox(width: 16),
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(name, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 15, color: PdfColors.brown)),
                pw.Text('$sold terjual', style: pw.TextStyle(color: PdfColors.grey600, fontSize: 12)),
              ],
            ),
          ),
          pw.Text(amount, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.orange700)),
        ],
      ),
    );
  }
}