// lib/service/pdf_service.dart
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';
import 'dart:typed_data';
import 'dart:math' as math;

class PdfService {
  static Future<Uint8List> generateFinancialReport({
    required String selectedDate,
    required String revenue,
    required String netProfit,
    required List<double> chartData,
    required List<dynamic> bestSelling,
  }) async {
    final pdf = pw.Document();
    
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Container(
            padding: pw.EdgeInsets.all(20),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                // Header
                pw.Text(
                  'Financial Income Report',
                  style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.orange800),
                ),
                pw.SizedBox(height: 10),
                pw.Text(
                  'Period: ${DateFormat('dd MMMM yyyy').format(DateTime.parse(selectedDate))}',
                  style: pw.TextStyle(fontSize: 14, color: PdfColors.grey700),
                ),
                pw.Text(
                  'Report Date: ${DateFormat('dd MMMM yyyy HH:mm').format(DateTime.now())}',
                  style: pw.TextStyle(fontSize: 12, color: PdfColors.grey600),
                ),
                pw.Divider(),
                pw.SizedBox(height: 20),
                
                // Summary Cards
                pw.Row(
                  children: [
                    _buildSummaryCard('Total Revenue', revenue),
                    pw.SizedBox(width: 20),
                    _buildSummaryCard('Net Profit (40%)', netProfit),
                  ],
                ),
                pw.SizedBox(height: 30),
                
                // Chart Section
                pw.Text('7 Day Trend', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.brown)),
                pw.SizedBox(height: 16),
                _buildSimpleChart(chartData), // Gunakan versi sederhana
                pw.SizedBox(height: 30),
                
                // Best Selling Section
                pw.Text('Best Selling Products', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.brown)),
                pw.SizedBox(height: 16),
                if (bestSelling.isEmpty)
                  pw.Text('No sales data yet', style: pw.TextStyle(color: PdfColors.grey600))
                else
                  ...bestSelling.asMap().entries.map((entry) {
                    final item = entry.value;
                    final rank = entry.key + 1;
                    return _buildBestSellingItem(
                      rank: rank,
                      name: item['name'].toString(),
                      sold: int.parse(item['sold'].toString()),
                      amount: item['amount'].toString(),
                    );
                  }),
                
                pw.SizedBox(height: 40),
                pw.Align(
                  alignment: pw.Alignment.center,
                  child: pw.Text(
                    'Generated by Pangsit Njedok App',
                    style: pw.TextStyle(fontSize: 10, color: PdfColors.grey500),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
    
    return pdf.save();
  }
  
  static pw.Container _buildSummaryCard(String title, String value) {
    return pw.Container(
      width: 200,
      padding: pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.orange200),
        borderRadius: pw.BorderRadius.circular(12),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(title, style: pw.TextStyle(color: PdfColors.grey600, fontSize: 11)),
          pw.SizedBox(height: 8),
          pw.Text(
            value,
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: PdfColors.brown),
          ),
        ],
      ),
    );
  }
  
  // VERSI SEDERHANA - Menggunakan Table untuk membuat grafik batang
  static pw.Widget _buildSimpleChart(List<double> points) {
    final maxValue = points.reduce(math.max);
    final minValue = points.reduce(math.min);
    
    return pw.Container(
      padding: pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.orange200),
        borderRadius: pw.BorderRadius.circular(12),
      ),
      child: pw.Column(
        children: [
          // Header hari
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
            children: List.generate(7, (index) {
              final date = DateTime.now().subtract(Duration(days: 6 - index));
              return pw.Expanded(
                child: pw.Text(
                  DateFormat('E').format(date),
                  style: pw.TextStyle(fontSize: 10),
                  textAlign: pw.TextAlign.center,
                ),
              );
            }),
          ),
          pw.SizedBox(height: 10),
          
          // Bar chart
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: List.generate(points.length, (index) {
              final height = (points[index] / maxValue) * 100;
              return pw.Expanded(
                child: pw.Column(
                  children: [
                    pw.Container(
                      height: height,
                      width: 20,
                      decoration: pw.BoxDecoration(
                        color: PdfColors.orange400,
                        borderRadius: pw.BorderRadius.vertical(top: pw.Radius.circular(4)),
                      ),
                    ),
                    pw.SizedBox(height: 5),
                    pw.Text(
                      '${(points[index] * 100).toStringAsFixed(0)}%',
                      style: pw.TextStyle(fontSize: 8),
                    ),
                  ],
                ),
              );
            }),
          ),
          
          pw.SizedBox(height: 16),
          
          // Nilai min dan max
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('Min: ${(minValue * 100).toStringAsFixed(0)}%', style: pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
              pw.Text('Max: ${(maxValue * 100).toStringAsFixed(0)}%', style: pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
            ],
          ),
        ],
      ),
    );
  }
  
  static pw.Container _buildBestSellingItem({
    required int rank,
    required String name,
    required int sold,
    required String amount,
  }) {
    final bool isTop = rank <= 3;
    
    return pw.Container(
      margin: pw.EdgeInsets.only(bottom: 12),
      padding: pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: isTop ? PdfColors.orange50 : PdfColors.white,
        border: pw.Border.all(color: isTop ? PdfColors.orange400 : PdfColors.orange200),
        borderRadius: pw.BorderRadius.circular(16),
      ),
      child: pw.Row(
        children: [
          // Circle untuk nomor rank
          pw.Container(
            width: 32,
            height: 32,
            decoration: pw.BoxDecoration(
              color: isTop ? PdfColors.orange400 : PdfColors.orange200,
              shape: pw.BoxShape.circle,
            ),
            child: pw.Center(
              child: pw.Text(
                '$rank',
                style: pw.TextStyle(color: PdfColors.white, fontWeight: pw.FontWeight.bold, fontSize: 14),
              ),
            ),
          ),
          pw.SizedBox(width: 16),
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(name, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 15, color: PdfColors.brown)),
                pw.Text('$sold portions sold', style: pw.TextStyle(color: PdfColors.grey600, fontSize: 12)),
              ],
            ),
          ),
          pw.Text(amount, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.orange700)),
        ],
      ),
    );
  }
}