import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Frame3(),
        ]),
      ),
    );
  }
}

class Frame3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 32,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: const Color(0xFFF5CB58)),
          child: Stack(
            children: [
              Positioned(
                left: 35,
                top: 9,
                child: SizedBox(
                  width: 30,
                  height: 14,
                  child: Text(
                    '16:04',
                    style: TextStyle(
                      color: const Color(0xFF391713),
                      fontSize: 13,
                      fontFamily: 'League Spartan',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
        Container(
          width: 26,
          height: 26,
          decoration: ShapeDecoration(
            color: const Color(0xFFF5F5F5),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(10),
            ),
          ),
          child: Stack(),
        ),
        Container(
          width: 26,
          height: 26,
          decoration: ShapeDecoration(
            color: const Color(0xFFF5F5F5),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(10),
            ),
          ),
          child: Stack(),
        ),
        Container(
          width: 47,
          height: 15,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(),
        ),
        Text.rich(
          TextSpan(
            children: [
              TextSpan(
                text: 'menu ',
                style: TextStyle(
                  color: const Color(0xFF391713),
                  fontSize: 18,
                  fontFamily: 'Poppins',
                  fontWeight: FontWeight.w600,
                  shadows: [Shadow(offset: Offset(0, 4), blurRadius: 4, color: Color(0xFF000000).withOpacity(0.25))],
                ),
              ),
              TextSpan(
                text: 'best seller',
                style: TextStyle(
                  color: const Color(0xFF391713),
                  fontSize: 18,
                  fontStyle: FontStyle.italic,
                  fontFamily: 'Poppins',
                  fontWeight: FontWeight.w600,
                  shadows: [Shadow(offset: Offset(0, 4), blurRadius: 4, color: Color(0xFF000000).withOpacity(0.25))],
                ),
              ),
              TextSpan(
                text: ' kami!',
                style: TextStyle(
                  color: const Color(0xFF391713),
                  fontSize: 18,
                  fontFamily: 'Poppins',
                  fontWeight: FontWeight.w600,
                  shadows: [Shadow(offset: Offset(0, 4), blurRadius: 4, color: Color(0xFF000000).withOpacity(0.25))],
                ),
              ),
            ],
          ),
        ),
        Container(
          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
          width: 49,
          height: 75,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 77,
                child: SizedBox(
                  width: 11,
                  child: Transform(
                    transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                    child: Text(
                      'Minuman',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: const Color(0xFF391713),
                        fontSize: 12,
                        fontFamily: 'League Spartan',
                        fontWeight: FontWeight.w400,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 62,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                  width: 62,
                  height: 49,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFF3E9B5),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(30),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 14,
                        top: 12.50,
                        child: Container(
                          width: 21.14,
                          height: 37,
                          child: Stack(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
        Container(
          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
          width: 394,
          height: 282,
          decoration: ShapeDecoration(
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(36),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 394,
                top: 0,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                  width: 282,
                  height: 394,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/282x394"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
        Container(
          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
          width: 49,
          height: 75,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 77,
                child: SizedBox(
                  width: 11,
                  child: Transform(
                    transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                    child: Text(
                      'Makanan',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: const Color(0xFF391713),
                        fontSize: 12,
                        fontFamily: 'League Spartan',
                        fontWeight: FontWeight.w400,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 62,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                  width: 62,
                  height: 49,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFF5CB58),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(30),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 16,
                        top: 12.50,
                        child: Container(
                          width: 17.34,
                          height: 37,
                          child: Stack(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
        Container(
          width: 68,
          height: 4,
          decoration: ShapeDecoration(
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            shadows: [
              BoxShadow(
                color: Color(0x3F000000),
                blurRadius: 4,
                offset: Offset(0, 4),
                spreadRadius: 0,
              )
            ],
          ),
          child: Stack(
            children: [
              Positioned(
                left: 24,
                top: 0,
                child: Container(
                  width: 20,
                  height: 4,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFF3E9B5),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 48,
                top: 0,
                child: Container(
                  width: 20,
                  height: 4,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFF3E9B5),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 20,
                  height: 4,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFE93C22),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
        Container(
          width: 393,
          height: 94,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 32,
                child: Container(
                  width: 393,
                  height: 62,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFE93C22),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(20),
                        topRight: Radius.circular(20),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 34.40,
                top: 15,
                child: Container(
                  width: 44.82,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFE93C22),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 44.83,
                top: 19,
                child: Container(
                  width: 25.02,
                  height: 24,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 148.03,
                top: 49,
                child: Container(
                  width: 25.11,
                  height: 24.09,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
            ],
          ),
        ),
        Container(
          width: 394,
          height: 845,
          child: Stack(
            children: [
              Positioned(
                left: 1,
                top: 0,
                child: Container(
                  width: 393,
                  height: 845,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFE95322),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(30),
                        topRight: Radius.circular(30),
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
        Container(
          width: 340,
          height: 551,
          child: Stack(
            children: [
              Positioned(
                left: 97,
                top: 150,
                child: Container(
                  width: 33,
                  height: 14,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFE95322),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(30),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 1,
                        top: 5,
                        child: SizedBox(
                          width: 21,
                          height: 6,
                          child: Text(
                            '4.0',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: const Color(0xFFF5F5F5),
                              fontSize: 12,
                              fontFamily: 'League Spartan',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 89,
                top: 154,
                child: Container(
                  width: 5,
                  height: 5,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFE93C22),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 12,
                top: 147,
                child: Text(
                  'Pork Skewer',
                  style: TextStyle(
                    color: const Color(0xFF391713),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 128,
                child: Text(
                  'Pangsit Tulang Rangu',
                  style: TextStyle(
                    color: const Color(0xFF391713),
                    fontSize: 13,
                    fontFamily: 'League Spartan',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 11,
                top: 146,
                child: Text(
                  'Rp.15.000',
                  style: TextStyle(
                    color: const Color(0xFF391713),
                    fontSize: 15,
                    fontFamily: 'League Spartan',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 96,
                top: 143,
                child: Container(
                  width: 57,
                  height: 19,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(11.88),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 40.38,
                        top: 1.19,
                        child: Container(
                          width: 16.63,
                          height: 16.63,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(11.88),
                            ),
                          ),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 1.19,
                        child: Container(
                          width: 16.63,
                          height: 16.63,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(11.88),
                            ),
                          ),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 26.13,
                        top: 5.56,
                        child: Text(
                          '1',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFF391713),
                            fontSize: 12,
                            fontFamily: 'League Spartan',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 272,
                top: 144,
                child: Container(
                  width: 57,
                  height: 19,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(11.88),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 40.38,
                        top: 1.19,
                        child: Container(
                          width: 16.63,
                          height: 16.63,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(11.88),
                            ),
                          ),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 1.19,
                        child: Container(
                          width: 16.63,
                          height: 16.63,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(11.88),
                            ),
                          ),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 25.13,
                        top: 5.56,
                        child: Text(
                          '0',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFF391713),
                            fontSize: 12,
                            fontFamily: 'League Spartan',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 223,
                top: 128,
                child: Text(
                  'Oseng Pangsit',
                  style: TextStyle(
                    color: const Color(0xFF391713),
                    fontSize: 13,
                    fontFamily: 'League Spartan',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 188,
                top: 146,
                child: Text(
                  'Rp.15.000',
                  style: TextStyle(
                    color: const Color(0xFF391713),
                    fontSize: 15,
                    fontFamily: 'League Spartan',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 140,
                top: 123,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                  width: 118,
                  height: 123,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 118,
                        top: 0,
                        child: Container(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                          width: 123,
                          height: 118,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/123x118"),
                              fit: BoxFit.fill,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(36),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 420.08,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                  width: 232.08,
                  height: 123,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 123,
                        top: 0,
                        child: Container(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                          width: 118,
                          height: 123,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/118x123"),
                              fit: BoxFit.fill,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(36),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 317,
                top: 311,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                  width: 118,
                  height: 123,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 118,
                        top: 0,
                        child: Container(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                          width: 123,
                          height: 118,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/123x118"),
                              fit: BoxFit.fill,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(36),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 11,
                top: 334,
                child: Text(
                  'Rp.15.000',
                  style: TextStyle(
                    color: const Color(0xFF391713),
                    fontSize: 15,
                    fontFamily: 'League Spartan',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 188,
                top: 334,
                child: Text(
                  'Rp.15.000',
                  style: TextStyle(
                    color: const Color(0xFF391713),
                    fontSize: 15,
                    fontFamily: 'League Spartan',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 28,
                top: 316,
                child: Text(
                  'Pangsit Tulang Rangu',
                  style: TextStyle(
                    color: const Color(0xFF391713),
                    fontSize: 13,
                    fontFamily: 'League Spartan',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 200,
                top: 316,
                child: Text(
                  'Pangsit Tulang Rangu',
                  style: TextStyle(
                    color: const Color(0xFF391713),
                    fontSize: 13,
                    fontFamily: 'League Spartan',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 94,
                top: 331,
                child: Container(
                  width: 57,
                  height: 19,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(11.88),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 40.38,
                        top: 1.19,
                        child: Container(
                          width: 16.63,
                          height: 16.63,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(11.88),
                            ),
                          ),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 1.19,
                        child: Container(
                          width: 16.63,
                          height: 16.63,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(11.88),
                            ),
                          ),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 25.13,
                        top: 5.56,
                        child: Text(
                          '0',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFF391713),
                            fontSize: 12,
                            fontFamily: 'League Spartan',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 272,
                top: 333,
                child: Container(
                  width: 57,
                  height: 19,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(11.88),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 40.38,
                        top: 1.19,
                        child: Container(
                          width: 16.63,
                          height: 16.63,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(11.88),
                            ),
                          ),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 1.19,
                        child: Container(
                          width: 16.63,
                          height: 16.63,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(11.88),
                            ),
                          ),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 25.13,
                        top: 5.56,
                        child: Text(
                          '0',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFF391713),
                            fontSize: 12,
                            fontFamily: 'League Spartan',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 23,
                top: 608.08,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                  width: 232.08,
                  height: 123,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 123,
                        top: 0,
                        child: Container(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                          width: 121,
                          height: 123,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/121x123"),
                              fit: BoxFit.fill,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(36),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 317,
                top: 497,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                  width: 118,
                  height: 121,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 118,
                        top: 0,
                        child: Container(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                          width: 121,
                          height: 118,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/121x118"),
                              fit: BoxFit.fill,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(36),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 98,
                top: 526,
                child: Container(
                  width: 57,
                  height: 19,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(11.88),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 40.38,
                        top: 1.19,
                        child: Container(
                          width: 16.63,
                          height: 16.63,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(11.88),
                            ),
                          ),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 1.19,
                        child: Container(
                          width: 16.63,
                          height: 16.63,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(11.88),
                            ),
                          ),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 25.13,
                        top: 5.56,
                        child: Text(
                          '0',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFF391713),
                            fontSize: 12,
                            fontFamily: 'League Spartan',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 276,
                top: 526,
                child: Container(
                  width: 57,
                  height: 19,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(11.88),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 40.38,
                        top: 1.19,
                        child: Container(
                          width: 16.63,
                          height: 16.63,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(11.88),
                            ),
                          ),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 1.19,
                        child: Container(
                          width: 16.63,
                          height: 16.63,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(11.88),
                            ),
                          ),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 25.13,
                        top: 5.56,
                        child: Text(
                          '0',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFF391713),
                            fontSize: 12,
                            fontFamily: 'League Spartan',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 11,
                top: 529,
                child: Text(
                  'Rp.15.000',
                  style: TextStyle(
                    color: const Color(0xFF391713),
                    fontSize: 15,
                    fontFamily: 'League Spartan',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 189,
                top: 529,
                child: Text(
                  'Rp.15.000',
                  style: TextStyle(
                    color: const Color(0xFF391713),
                    fontSize: 15,
                    fontFamily: 'League Spartan',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 30,
                top: 508,
                child: Text(
                  'Pangsit Tulang Rangu',
                  style: TextStyle(
                    color: const Color(0xFF391713),
                    fontSize: 13,
                    fontFamily: 'League Spartan',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 199,
                top: 508,
                child: Text(
                  'Pangsit Tulang Rangu',
                  style: TextStyle(
                    color: const Color(0xFF391713),
                    fontSize: 13,
                    fontFamily: 'League Spartan',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 197,
                top: 238.08,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                  width: 232.08,
                  height: 123,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 123,
                        top: 0,
                        child: Container(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                          width: 118,
                          height: 123,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/118x123"),
                              fit: BoxFit.fill,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(36),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}